export default {
    code: 0,
    msg: null,
    data: [
        {
            id: 11000,
            parentId: -1,
            code: null,
            name: '首页',
            children: [],
            hasChildren: false,
            icon: '',
            spread: false,
            path: 'home',
            keepAlive: '0',
            permission: null,
            type: '0',
            label: '首页',
            sort: 3,
        },
        {
            id: 12000,
            parentId: -1,
            code: null,
            name: '管理中心',
            children: [
                {
                    id: 12100,
                    parentId: 12000,
                    code: null,
                    name: '人员管理',
                    children: [
                        {
                            id: 20002,
                            parentId: 12100,
                            code: null,
                            name: '人员动态',
                            children: [],
                            hasChildren: false,
                            icon: null,
                            spread: false,
                            path: 'peopleDynamics',
                            keepAlive: '0',
                            permission: null,
                            type: '0',
                            label: '人员动态',
                            sort: 0,
                        },
                        {
                            id: 20003,
                            parentId: 12100,
                            code: null,
                            name: '人员信息',
                            children: [],
                            hasChildren: false,
                            icon: null,
                            spread: false,
                            path: 'staffInformation',
                            keepAlive: '0',
                            permission: null,
                            type: '0',
                            label: '人员信息',
                            sort: 1,
                        },
                        {
                            id: 20004,
                            parentId: 12100,
                            code: null,
                            name: '人员轨迹',
                            children: [],
                            hasChildren: false,
                            icon: null,
                            spread: false,
                            path: 'personnelTrack',
                            keepAlive: '0',
                            permission: null,
                            type: '0',
                            label: '人员轨迹',
                            sort: 2,
                        },
                    ],
                    hasChildren: true,
                    icon: 'icon-rizhiguanli',
                    spread: false,
                    path: 'peopleManagement',
                    keepAlive: '0',
                    permission: null,
                    type: '0',
                    label: '人员管理',
                    sort: 0,
                },
                {
                    id: 12200,
                    parentId: 12000,
                    code: null,
                    name: '排班管理',
                    children: [
                        {
                            id: 20005,
                            parentId: 12200,
                            code: null,
                            name: '排班管理',
                            children: [],
                            hasChildren: false,
                            icon: null,
                            spread: false,
                            path: 'scheduleIndex',
                            keepAlive: '0',
                            permission: null,
                            type: '0',
                            label: '排班管理',
                            sort: 0,
                        },
                        {
                            id: 20006,
                            parentId: 12200,
                            code: null,
                            name: '班次管理',
                            children: [],
                            hasChildren: false,
                            icon: null,
                            spread: false,
                            path: 'shiftManagementIndex',
                            keepAlive: '0',
                            permission: null,
                            type: '0',
                            label: '班次管理',
                            sort: 1,
                        },
                    ],
                    hasChildren: true,
                    icon: 'icon-navicon-zdgl',
                    spread: false,
                    path: 'scheduleManagement',
                    keepAlive: '0',
                    permission: null,
                    type: '0',
                    label: '排班管理',
                    sort: 1,
                },
                {
                    id: 12300,
                    parentId: 12000,
                    code: null,
                    name: '运营管理',
                    children: [
                        {
                            id: 123001,
                            parentId: 12300,
                            code: null,
                            name: '运营管理',
                            children: [],
                            hasChildren: false,
                            icon: null,
                            spread: false,
                            path: 'http://property-st.ienjoys.com/xxlst/#/home',
                            keepAlive: '0',
                            permission: null,
                            type: '0',
                            label: '运营管理',
                            sort: 1,
                        },
                    ],
                    hasChildren: true,
                    icon: null,
                    spread: false,
                    path: 'operationManage',
                    keepAlive: '0',
                    permission: null,
                    type: '0',
                    label: '运营管理',
                    sort: 3,
                },
            ],
            hasChildren: true,
            icon: '',
            spread: false,
            path: 'managementCenter',
            keepAlive: '0',
            permission: null,
            type: '0',
            label: '管理中心',
            sort: 4,
        },
    ],
};
